/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as DocsRouteImport } from "./routes/docs";
import { Route as DocsIndexRouteImport } from "./routes/docs/index";
import { Route as DocsInstallRouteImport } from "./routes/docs/install";
import { Route as DocsMcpRouteImport } from "./routes/docs/mcp";
import { Route as DocsQuickstartRouteImport } from "./routes/docs/quickstart";
import { Route as DocsRoadmapFaqRouteImport } from "./routes/docs/roadmap-faq";
import { Route as DocsSecurityRouteImport } from "./routes/docs/security";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsRoute = DocsRouteImport.update({
  id: "/docs",
  path: "/docs",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DocsRoute,
} as any);
const DocsInstallRoute = DocsInstallRouteImport.update({
  id: "/install",
  path: "/install",
  getParentRoute: () => DocsRoute,
} as any);
const DocsMcpRoute = DocsMcpRouteImport.update({
  id: "/mcp",
  path: "/mcp",
  getParentRoute: () => DocsRoute,
} as any);
const DocsQuickstartRoute = DocsQuickstartRouteImport.update({
  id: "/quickstart",
  path: "/quickstart",
  getParentRoute: () => DocsRoute,
} as any);
const DocsRoadmapFaqRoute = DocsRoadmapFaqRouteImport.update({
  id: "/roadmap-faq",
  path: "/roadmap-faq",
  getParentRoute: () => DocsRoute,
} as any);
const DocsSecurityRoute = DocsSecurityRouteImport.update({
  id: "/security",
  path: "/security",
  getParentRoute: () => DocsRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/docs": typeof DocsRouteWithChildren;
  "/docs/install": typeof DocsInstallRoute;
  "/docs/mcp": typeof DocsMcpRoute;
  "/docs/quickstart": typeof DocsQuickstartRoute;
  "/docs/roadmap-faq": typeof DocsRoadmapFaqRoute;
  "/docs/security": typeof DocsSecurityRoute;
  "/docs/": typeof DocsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/docs/install": typeof DocsInstallRoute;
  "/docs/mcp": typeof DocsMcpRoute;
  "/docs/quickstart": typeof DocsQuickstartRoute;
  "/docs/roadmap-faq": typeof DocsRoadmapFaqRoute;
  "/docs/security": typeof DocsSecurityRoute;
  "/docs": typeof DocsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/docs": typeof DocsRouteWithChildren;
  "/docs/install": typeof DocsInstallRoute;
  "/docs/mcp": typeof DocsMcpRoute;
  "/docs/quickstart": typeof DocsQuickstartRoute;
  "/docs/roadmap-faq": typeof DocsRoadmapFaqRoute;
  "/docs/security": typeof DocsSecurityRoute;
  "/docs/": typeof DocsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/docs"
    | "/docs/install"
    | "/docs/mcp"
    | "/docs/quickstart"
    | "/docs/roadmap-faq"
    | "/docs/security"
    | "/docs/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/docs/install"
    | "/docs/mcp"
    | "/docs/quickstart"
    | "/docs/roadmap-faq"
    | "/docs/security"
    | "/docs";
  id:
    | "__root__"
    | "/"
    | "/docs"
    | "/docs/install"
    | "/docs/mcp"
    | "/docs/quickstart"
    | "/docs/roadmap-faq"
    | "/docs/security"
    | "/docs/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DocsRoute: typeof DocsRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs": {
      id: "/docs";
      path: "/docs";
      fullPath: "/docs";
      preLoaderRoute: typeof DocsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/": {
      id: "/docs/";
      path: "/";
      fullPath: "/docs/";
      preLoaderRoute: typeof DocsIndexRouteImport;
      parentRoute: typeof DocsRoute;
    };
    "/docs/install": {
      id: "/docs/install";
      path: "/install";
      fullPath: "/docs/install";
      preLoaderRoute: typeof DocsInstallRouteImport;
      parentRoute: typeof DocsRoute;
    };
    "/docs/mcp": {
      id: "/docs/mcp";
      path: "/mcp";
      fullPath: "/docs/mcp";
      preLoaderRoute: typeof DocsMcpRouteImport;
      parentRoute: typeof DocsRoute;
    };
    "/docs/quickstart": {
      id: "/docs/quickstart";
      path: "/quickstart";
      fullPath: "/docs/quickstart";
      preLoaderRoute: typeof DocsQuickstartRouteImport;
      parentRoute: typeof DocsRoute;
    };
    "/docs/roadmap-faq": {
      id: "/docs/roadmap-faq";
      path: "/roadmap-faq";
      fullPath: "/docs/roadmap-faq";
      preLoaderRoute: typeof DocsRoadmapFaqRouteImport;
      parentRoute: typeof DocsRoute;
    };
    "/docs/security": {
      id: "/docs/security";
      path: "/security";
      fullPath: "/docs/security";
      preLoaderRoute: typeof DocsSecurityRouteImport;
      parentRoute: typeof DocsRoute;
    };
  }
}

interface DocsRouteChildren {
  DocsInstallRoute: typeof DocsInstallRoute;
  DocsMcpRoute: typeof DocsMcpRoute;
  DocsQuickstartRoute: typeof DocsQuickstartRoute;
  DocsRoadmapFaqRoute: typeof DocsRoadmapFaqRoute;
  DocsSecurityRoute: typeof DocsSecurityRoute;
  DocsIndexRoute: typeof DocsIndexRoute;
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsInstallRoute: DocsInstallRoute,
  DocsMcpRoute: DocsMcpRoute,
  DocsQuickstartRoute: DocsQuickstartRoute,
  DocsRoadmapFaqRoute: DocsRoadmapFaqRoute,
  DocsSecurityRoute: DocsSecurityRoute,
  DocsIndexRoute: DocsIndexRoute,
};

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
