//go:build dev

package devlocal

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
)

// HubOptions describe the generated .dev/hub.yaml.
type HubOptions struct {
	Targets   []Target
	UsersFile string // e.g. hack/users.dev.yaml
	KeyFile   string // e.g. hack/dev.key
	// SQLitePath, when set, uses the sqlite store there instead of memory.
	SQLitePath string
	// AI is "" (Ask AI off), "anthropic" or "bedrock"; see AIFromEnv.
	AI AIOptions
}

// AIOptions select the Ask AI provider of a local hub.
type AIOptions struct {
	Provider         string // "", anthropic or bedrock
	AnthropicModel   string // optional; the hub has a default
	BedrockRegion    string
	BedrockModelID   string
	GuardrailID      string
	GuardrailVersion string
}

// AIFromEnv reads the explicit Ask AI settings of a local setup:
// EDDY_AI_PROVIDER (empty = off, anthropic or bedrock); for anthropic
// ANTHROPIC_API_KEY (required, read by the hub at runtime) and EDDY_AI_MODEL;
// for bedrock EDDY_BEDROCK_REGION and EDDY_BEDROCK_MODEL_ID (required) and
// EDDY_BEDROCK_GUARDRAIL_ID/_VERSION. Bedrock credentials come from the AWS
// default chain (use AWS_PROFILE locally), never from the generated file.
func AIFromEnv(getenv func(string) string) (AIOptions, error) {
	o := AIOptions{Provider: strings.TrimSpace(getenv("EDDY_AI_PROVIDER"))}
	switch o.Provider {
	case "":
		return o, nil
	case "anthropic":
		if getenv("ANTHROPIC_API_KEY") == "" {
			return o, errors.New("EDDY_AI_PROVIDER=anthropic needs ANTHROPIC_API_KEY")
		}
		o.AnthropicModel = getenv("EDDY_AI_MODEL")
	case "bedrock":
		o.BedrockRegion, o.BedrockModelID = getenv("EDDY_BEDROCK_REGION"), getenv("EDDY_BEDROCK_MODEL_ID")
		o.GuardrailID, o.GuardrailVersion = getenv("EDDY_BEDROCK_GUARDRAIL_ID"), getenv("EDDY_BEDROCK_GUARDRAIL_VERSION")
		var missing []string
		if o.BedrockRegion == "" {
			missing = append(missing, "EDDY_BEDROCK_REGION")
		}
		if o.BedrockModelID == "" {
			missing = append(missing, "EDDY_BEDROCK_MODEL_ID")
		}
		if (o.GuardrailID == "") != (o.GuardrailVersion == "") {
			missing = append(missing, "both EDDY_BEDROCK_GUARDRAIL_ID and EDDY_BEDROCK_GUARDRAIL_VERSION")
		}
		if len(missing) > 0 {
			return o, fmt.Errorf("EDDY_AI_PROVIDER=bedrock needs %s", strings.Join(missing, ", "))
		}
	default:
		return o, fmt.Errorf("EDDY_AI_PROVIDER=%q is not supported (leave it empty, anthropic or bedrock)", o.Provider)
	}
	return o, nil
}

// palette colours unprotected clusters in order; protected ones are red.
var palette = []string{"#0F766E", "#1D4ED8", "#7C3AED", "#B45309", "#0369A1", "#15803D", "#BE185D", "#4D7C0F"}

const protectedColor = "#B91C1C"

// q quotes s as a JSON string, which is also a valid YAML scalar.
func q(s string) string {
	b, _ := json.Marshal(s)
	return string(b)
}

// RenderHub returns the hub.yaml for a local setup: loopback listeners, the
// Vite origin as publicURL, dev fake login, local users, MCP on, and one
// static cluster per target sharing the TokenEnv agent token.
func RenderHub(o HubOptions) []byte {
	var b bytes.Buffer
	w := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }
	w("# Generated by `go run -tags dev ./cmd/hub dev-config` (task dev). Do not edit:\n")
	w("# it is rewritten on every `task dev`. DEV ONLY, never use it for a real install.\n")
	w("publicURL: http://localhost:5173\n")
	w("listen:\n  ui: 127.0.0.1:8080\n  agents: 127.0.0.1:8443\n  metrics: 127.0.0.1:9090\n")
	w("auth:\n  local:\n    enabled: true\n    usersFile: %s\n  keyFile: %s\n", q(o.UsersFile), q(o.KeyFile))
	if o.SQLitePath != "" {
		w("store:\n  driver: sqlite\n  path: %s\n", q(o.SQLitePath))
	} else {
		w("store:\n  driver: memory\n")
	}
	switch ai := o.AI; ai.Provider {
	case "anthropic":
		w("ai:\n  enabled: true\n  provider: anthropic\n  anthropic:\n    apiKeyEnv: ANTHROPIC_API_KEY\n")
		if ai.AnthropicModel != "" {
			w("    model: %s\n", q(ai.AnthropicModel))
		}
	case "bedrock":
		w("ai:\n  enabled: true\n  provider: bedrock\n  bedrock:\n    region: %s\n    modelId: %s\n", q(ai.BedrockRegion), q(ai.BedrockModelID))
		if ai.GuardrailID != "" {
			w("    guardrail:\n      id: %s\n      version: %s\n", q(ai.GuardrailID), q(ai.GuardrailVersion))
		}
	default:
		w("ai:\n  enabled: false\n")
	}
	w("mcp:\n  enabled: true\n  writes: true\n  protectedClusters: confirm\n")
	w("dev:\n  fakeLogin: true\n")
	w("staticClusters:\n")
	color := 0
	for i, t := range o.Targets {
		c := protectedColor
		if !t.Protected {
			c = palette[color%len(palette)]
			color++
		}
		w("  - name: %s\n", q(t.Cluster))
		w("    displayName: %s\n", q(t.Cluster))
		// ParseHub expands ${ENV}; a "$" in a context name must not.
		w("    environment: %s\n", q("local · "+strings.ReplaceAll(t.Context, "$", "")))
		w("    color: %s\n", q(c))
		w("    protected: %t\n", t.Protected)
		w("    order: %d\n", i+1)
		w("    tokenEnv: %s\n", TokenEnv)
	}
	return b.Bytes()
}
