{{- if not .Values.users.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: eddy-users
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eddy-hub.labels" . | nindent 4 }}
type: Opaque
stringData:
  users.yaml: |
    {{- if .Values.users.list }}
    {{- toYaml (dict "users" .Values.users.list) | nindent 4 }}
    {{- else }}
    users: []
    {{- end }}
{{- end }}
