{{- if and .Values.token.value (not .Values.token.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eddy-agent.tokenSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eddy-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.token.key }}: {{ .Values.token.value | quote }}
{{- end }}
{{- if .Values.hub.caBundle }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eddy-agent.fullname" . }}-hub-ca
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eddy-agent.labels" . | nindent 4 }}
data:
  ca.crt: |
    {{- .Values.hub.caBundle | nindent 4 }}
{{- end }}
