/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AppRouteImport } from "./routes/_app";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as AppIndexRouteImport } from "./routes/_app/index";
import { Route as AppAuditRouteImport } from "./routes/_app/audit";
import { Route as AppFleetRouteImport } from "./routes/_app/fleet";
import { Route as AppThreadsRouteImport } from "./routes/_app/threads";
import { Route as AppCClusterRouteRouteImport } from "./routes/_app/c/$cluster/route";
import { Route as AppSettingsTokensRouteImport } from "./routes/_app/settings/tokens";
import { Route as AppCClusterIndexRouteImport } from "./routes/_app/c/$cluster/index";
import { Route as AppCClusterRKindNsNameRouteImport } from "./routes/_app/c/$cluster/r/$kind/$ns/$name";

const AppRoute = AppRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AppIndexRoute = AppIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppRoute,
} as any);
const AppAuditRoute = AppAuditRouteImport.update({
  id: "/audit",
  path: "/audit",
  getParentRoute: () => AppRoute,
} as any);
const AppFleetRoute = AppFleetRouteImport.update({
  id: "/fleet",
  path: "/fleet",
  getParentRoute: () => AppRoute,
} as any);
const AppThreadsRoute = AppThreadsRouteImport.update({
  id: "/threads",
  path: "/threads",
  getParentRoute: () => AppRoute,
} as any);
const AppCClusterRouteRoute = AppCClusterRouteRouteImport.update({
  id: "/c/$cluster",
  path: "/c/$cluster",
  getParentRoute: () => AppRoute,
} as any);
const AppSettingsTokensRoute = AppSettingsTokensRouteImport.update({
  id: "/settings/tokens",
  path: "/settings/tokens",
  getParentRoute: () => AppRoute,
} as any);
const AppCClusterIndexRoute = AppCClusterIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppCClusterRouteRoute,
} as any);
const AppCClusterRKindNsNameRoute = AppCClusterRKindNsNameRouteImport.update({
  id: "/r/$kind/$ns/$name",
  path: "/r/$kind/$ns/$name",
  getParentRoute: () => AppCClusterRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof AppIndexRoute;
  "/login": typeof LoginRoute;
  "/audit": typeof AppAuditRoute;
  "/fleet": typeof AppFleetRoute;
  "/threads": typeof AppThreadsRoute;
  "/c/$cluster": typeof AppCClusterRouteRouteWithChildren;
  "/settings/tokens": typeof AppSettingsTokensRoute;
  "/c/$cluster/": typeof AppCClusterIndexRoute;
  "/c/$cluster/r/$kind/$ns/$name": typeof AppCClusterRKindNsNameRoute;
}
export interface FileRoutesByTo {
  "/login": typeof LoginRoute;
  "/audit": typeof AppAuditRoute;
  "/fleet": typeof AppFleetRoute;
  "/threads": typeof AppThreadsRoute;
  "/": typeof AppIndexRoute;
  "/settings/tokens": typeof AppSettingsTokensRoute;
  "/c/$cluster": typeof AppCClusterIndexRoute;
  "/c/$cluster/r/$kind/$ns/$name": typeof AppCClusterRKindNsNameRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_app": typeof AppRouteWithChildren;
  "/login": typeof LoginRoute;
  "/_app/audit": typeof AppAuditRoute;
  "/_app/fleet": typeof AppFleetRoute;
  "/_app/threads": typeof AppThreadsRoute;
  "/_app/": typeof AppIndexRoute;
  "/_app/c/$cluster": typeof AppCClusterRouteRouteWithChildren;
  "/_app/settings/tokens": typeof AppSettingsTokensRoute;
  "/_app/c/$cluster/": typeof AppCClusterIndexRoute;
  "/_app/c/$cluster/r/$kind/$ns/$name": typeof AppCClusterRKindNsNameRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/login"
    | "/audit"
    | "/fleet"
    | "/threads"
    | "/c/$cluster"
    | "/settings/tokens"
    | "/c/$cluster/"
    | "/c/$cluster/r/$kind/$ns/$name";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/login"
    | "/audit"
    | "/fleet"
    | "/threads"
    | "/"
    | "/settings/tokens"
    | "/c/$cluster"
    | "/c/$cluster/r/$kind/$ns/$name";
  id:
    | "__root__"
    | "/_app"
    | "/login"
    | "/_app/audit"
    | "/_app/fleet"
    | "/_app/threads"
    | "/_app/"
    | "/_app/c/$cluster"
    | "/_app/settings/tokens"
    | "/_app/c/$cluster/"
    | "/_app/c/$cluster/r/$kind/$ns/$name";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren;
  LoginRoute: typeof LoginRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_app": {
      id: "/_app";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AppRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_app/": {
      id: "/_app/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AppIndexRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/audit": {
      id: "/_app/audit";
      path: "/audit";
      fullPath: "/audit";
      preLoaderRoute: typeof AppAuditRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/fleet": {
      id: "/_app/fleet";
      path: "/fleet";
      fullPath: "/fleet";
      preLoaderRoute: typeof AppFleetRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/threads": {
      id: "/_app/threads";
      path: "/threads";
      fullPath: "/threads";
      preLoaderRoute: typeof AppThreadsRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/c/$cluster": {
      id: "/_app/c/$cluster";
      path: "/c/$cluster";
      fullPath: "/c/$cluster";
      preLoaderRoute: typeof AppCClusterRouteRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/settings/tokens": {
      id: "/_app/settings/tokens";
      path: "/settings/tokens";
      fullPath: "/settings/tokens";
      preLoaderRoute: typeof AppSettingsTokensRouteImport;
      parentRoute: typeof AppRoute;
    };
    "/_app/c/$cluster/": {
      id: "/_app/c/$cluster/";
      path: "/";
      fullPath: "/c/$cluster/";
      preLoaderRoute: typeof AppCClusterIndexRouteImport;
      parentRoute: typeof AppCClusterRouteRoute;
    };
    "/_app/c/$cluster/r/$kind/$ns/$name": {
      id: "/_app/c/$cluster/r/$kind/$ns/$name";
      path: "/r/$kind/$ns/$name";
      fullPath: "/c/$cluster/r/$kind/$ns/$name";
      preLoaderRoute: typeof AppCClusterRKindNsNameRouteImport;
      parentRoute: typeof AppCClusterRouteRoute;
    };
  }
}

interface AppCClusterRouteRouteChildren {
  AppCClusterIndexRoute: typeof AppCClusterIndexRoute;
  AppCClusterRKindNsNameRoute: typeof AppCClusterRKindNsNameRoute;
}

const AppCClusterRouteRouteChildren: AppCClusterRouteRouteChildren = {
  AppCClusterIndexRoute: AppCClusterIndexRoute,
  AppCClusterRKindNsNameRoute: AppCClusterRKindNsNameRoute,
};

const AppCClusterRouteRouteWithChildren =
  AppCClusterRouteRoute._addFileChildren(AppCClusterRouteRouteChildren);

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute;
  AppFleetRoute: typeof AppFleetRoute;
  AppThreadsRoute: typeof AppThreadsRoute;
  AppIndexRoute: typeof AppIndexRoute;
  AppCClusterRouteRoute: typeof AppCClusterRouteRouteWithChildren;
  AppSettingsTokensRoute: typeof AppSettingsTokensRoute;
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppFleetRoute: AppFleetRoute,
  AppThreadsRoute: AppThreadsRoute,
  AppIndexRoute: AppIndexRoute,
  AppCClusterRouteRoute: AppCClusterRouteRouteWithChildren,
  AppSettingsTokensRoute: AppSettingsTokensRoute,
};

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
